import '@/styles/destyle.css'
import '@/styles/globals.css'
import '@/styles/variables.css'
import type { Metadata } from 'next'
import "@fontsource/exo";
import "@fontsource/noto-sans-jp";
import "@fontsource/noto-sans-jp/700.css";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body>
        {children}
      </body>
    </html>
  )
}
